version: "3.9"
services:
  postgres:
    image: postgres:latest
    hostname: entirety-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  entirety:
    image: ghcr.io/n5geh/n5geh.tools.entirety2:development
    #    build:
    #      context: .
    #      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - static:/var/entirety/static/
      - media:/var/entirety/media/
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    hostname: ng
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/templates/
      - static:/var/entirety/static/
      - media:/var/entirety/media/
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      WEB_URL: ${WEB_URL:-localhost}
    depends_on:
      - entirety

volumes:
  static:
  pgdata:
  media:
