version: "3.9"
services:
  postgres:
    image: postgres:latest
    hostname: entirety-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  entirety:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - /var/entirety/static/:/var/entirety/static/
      - media:/var/entirety/media/
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    hostname: ng
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/entirety/static/:/var/entirety/static/
      - media:/var/entirety/media/
    depends_on:
      - entirety

volumes:
  pgdata:
  media:
