name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v10.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}

    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/publish-action@v10.2.0
      if: steps.release.outputs.released == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}
